name: build
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
      - development

permissions: read-all

jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install npm dependency
        run: npm install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install pod dependency
        run: |
          cd ios
          bundle exec pod install
      - name: Install bundler
        run: |
          cd ios
          gem install bundler
      - name: Install gem plugins
        run: |
          cd ios
          bundle install
  android-build:
    name: Android Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine infomation
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install npm dependency
        run: npm install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build
      - name: Install bundler
        run: |
          cd android
          gem install bundler
      - name: Install gem plugins
        run: |
          cd android
          bundle install
